apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: service-weatherapp-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-weatherapp-primary
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-weatherapp-primary
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: service-weatherapp-canary
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/name: service-weatherapp-primary
        app.kubernetes.io/part-of: project-weatherapp3
        app.kubernetes.io/version: latest
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: version=latest revision=1 releasename=project-weatherapp3-staging-service-weatherapp
            keptn_project=project-weatherapp3 keptn_service=service-weatherapp keptn_stage=staging
            keptn_deployment=primary
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['deployment']
        - name: CONTAINER_IMAGE
          value: docker.io/simonesan/hey-service:latest
        - name: KEPTN_PROJECT
          value: service-weatherapp
        - name: KEPTN_STAGE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KEPTN_SERVICE
          value: service-weatherapp
        - name: UNLEASH_SERVER_URL
          value: http://unleash.unleash-dev/api
        image: docker.io/simonesan/hey-service:latest
        imagePullPolicy: IfNotPresent
        name: service-weatherapp
        ports:
        - containerPort: 4200
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
status: {}
