apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: service-weatherapp-canary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4200
  selector:
    app: service-weatherapp
  type: ClusterIP
status:
  loadBalancer: {}
