apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: null
  name: service-weatherapp-canary
spec:
  host: service-weatherapp-canary.project-weatherapp3-staging.svc.cluster.local
